name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SONATYPE_USER: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make release
        run: |
          ./gradlew release \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}
      - name: Publish
        run: ./gradlew publish -DSONATYPE_USER=${SONATYPE_USER} -DSONATYPE_PASSWORD=${SONATYPE_PASSWORD}
